# Generated by Django 5.0.6 on 2024-10-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='manager',
        ),
    ]
