# Generated by Django 5.0.6 on 2024-10-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_created_by_project_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
