# Generated by Django 5.0.6 on 2024-10-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
